[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
    ignore:.*StarletteDeprecationWarning.*
    ignore:.*Using `httpx` with `starlette.testclient`.*
    ignore::DeprecationWarning
